// USER TYPES
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// UI TYPES
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const REMOVE_LOADING = "REMOVE_LOADING";
export const BACKDROP_SHOW = "BACKDROP_SHOW";
export const BACKDROP_HIDE = "BACKDROP_HIDE";
